### PR TITLE
updpkg to 1.10.0 and replace py2 dep w/ py3

### LINKED ISSUE #30: [gtest] Out of date
This package has been outdated for a while and I believe updating it will fix the bug as described in [gmock-bug](https://bugs.archlinux.org/task/63793?string=gmock&project=5&type%5B0%5D=&sev%5B0%5D=&pri%5B0%5D=&due%5B0%5D=&reported%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=)

### PR DESCRIPTION
**Pull request by acxz**
Resolves #30 
gtest does not use `configure` anymore so lines dealing with `*.ac` and related files are removed from the PKGBUILD.
All the tests pass with python3 so there is no need to build against python2.
Null pointer patch has been merged upstream.
`google{test,mock}/CHANGES` does not exist anymore
`scripts/g{test/mock}-config` also does not exist, but `scrips/g{test/mock}-config.in` does so I changed that. Maybe we do not even need to `install` those config files anyway. Not really sure what to do so I just took the safest route.

### CODE REVIEW

**Comment by acxz** [comment]
@anthraxx Do you mind taking a look at this PR?

**Comment by jwhendy** [comment]
This doesn't fix the realtime-tools issue for me, but I am able to build with the following adjustments to the current 1.8.1-3 package.
```
$ cd /usr/src/gmock
$ sudo mkdir src
$ cd ./src
$ sudo ln -s ../*.cc ./
$ cd ..
$ sudo wget -O CMakeLists.txt https://raw.githubusercontent.com/google/googletest/master/googlemock/CMakeLists.txt
$ sudo sed -i s,../googletest,../gtest, CMakeLists.txt
```

On this patch:
```$ ls -R /usr/src/gmock/
/usr/src/gmock/:
cmake  src  CMakeLists.txt

/usr/src/gmock/cmake:
gmock_main.pc.in  gmock.pc.in

/usr/src/gmock/src:
gmock-all.cc            gmock-internal-utils.cc  gmock-spec-builders.cc
gmock-cardinalities.cc  gmock_main.cc
gmock.cc                gmock-matchers.cc

```
Via my workaround above:
```
$ ls -R /usr/src/gmock/
/usr/src/gmock/:
src             gmock-cardinalities.cc   gmock_main.cc
CMakeLists.txt  gmock.cc                 gmock-matchers.cc
gmock-all.cc    gmock-internal-utils.cc  gmock-spec-builders.cc

/usr/src/gmock/src:
gmock-all.cc            gmock-internal-utils.cc  gmock-spec-builders.cc
gmock-cardinalities.cc  gmock_main.cc
gmock.cc                gmock-matchers.cc
```

On your patch, doing `sudo ln -s ./src/*.cc ./` (essentially the reverse of what I did) does *not* work, so there must be some other reason that this fails as the dir structures look identical with respect to `.cc` files.

**Comment by acxz** [comment]
@jwhendy ah yes, this PR doesn't attempt to resolve that issue. This is just to upgrade to gtest/gmock package.

**Comment by jwhendy** [comment]
Thanks for clarifying @acxz . I was going by the description:
>  I believe updating it will fix the bug as described in [gmock-bug](https://bugs.archlinux.org/task/63793)

Since it points to my bug report, which was created as part of fixing the `realtime-tools`, I assumed it was attempting to fix that. Did something else change the location of `/usr/src/gmock/*.cc` (they appear in `/usr/src/gmock/src/*.cc` with this PR)? Perhaps that was upstream... since I believe that's part of why `realtime-tools` fails and saw the change here, I assumed you made it.

Anyway, sorry for the confusion.

**Comment by acxz** [comment]
@anthraxx can u provide some closure to this PR?

**Comment by acxz** [comment]
@anthraxx can u take a look at this PR?

**Comment by acxz** [comment]
@anthraxx can u take a look at this PR?

**Comment by acxz** [comment]
Thx so much, @anthraxx!

**Comment by anthraxx** [comment]
thanks for the PR and sry for the delay, sometimes its hard to prioritize

**Comment by acxz** [comment]
yep totally understandable, just keep doing you man, you are doing great! Thank you for all the hard work you do, really man.

**Pull request merged**
