### PR TITLE
Some improvements to awesome PKGBUILD and update 4.0

### PR DESCRIPTION
**Pull request by xduugu**

### CODE REVIEW

**Comment by anthraxx** [comment]
cool thanks, can you please use https://github.com/awesomeWM/awesome/releases/download/v4.0/awesome-4.0.tar.xz.asc as source instead?

**Comment by xduugu** [comment]
I took the URLs from the [official download page](https://awesomewm.org/download/), but I can change them. However, I noticed that releases before 4.0 were not signed, so I have to move the commit after the 4.0 update commit.

**Comment by xduugu** [comment]
Sorry, took some time, but it should be fine now.

**Comment by anthraxx** [comment]
looks good so far... thanks. just thinking about if we need a news entry as the configuration may be incompatible.

**Comment by xduugu** [comment]
As far as I remember, the default configuration of 3.5.9 works with 4.0, but the old version of a library I use (tyrannical) did not play well with it. So, a news entry would not hurt, even though I think that most of awesome users are aware of its configuration breakage tradition. 😄

**Comment by anthraxx** [comment]
@xduugu thanks a lot for your contribution and help getting awesome 4.0 shipped, i applied all your changes. *happy*

**Pull request closed without merging**
