### PR TITLE
Updates synergy package to version 1.10.0

### PR DESCRIPTION
**Pull request by targodan**
I was forced to implement some nastiness in order to get everything
working.

1. Updated the patch to use system libs as opposed to bundled libs.
2. Had to add some include files to fix build with qt 5.11 (likely to be
obsolete in a future version, see: https://github.com/symless/synergy-core/pull/6359)
3. Building the tests was disabled without a nice way to enable it. Had
to `add_subdirectory` in the root CMake file.
4. Had to delete the file
`src/test/integtests/arch/ArchInternetTests.cpp`. This file contained a
reference to a macro `ARCH_INTERNET`. This macro however (or even this
string) exists *nowhere else* in the project, causing the build to fail.
Without the file everything is working fine.
5. Had to fix the test CMake files, as they wanted to link against
`synergy` which is a binary that does not export its symbols...

Feel free to ask if you wonder about anything I did, or if you want me to refine something.

PS: Yes, this is Luca. We had contact via mail recently. ;)

### CODE REVIEW

**Comment by anthraxx** [comment]
after reading the commits: This looks awesome! Thanks a lot.
I will apply this when building, really appreciate the great work here.

**Comment by targodan** [comment]
You're welcome. Looking forward to it. :smiley:

**Comment by anthraxx** [comment]
we need to backport some patches else the tests dont pass. need to figure out which commits are needed hm

**Comment by targodan** [comment]
Sorry bout the delay.

Do you have some information about the machine your building on? The way I committed it, it worked on my machine. Including the tests (unit tests of the software, or do you mean different tests).

**Comment by anthraxx** [comment]
Machine shouldn't matter, just try extra-x86_64-build from devtools :smile:

**Comment by targodan** [comment]
Ok, what error do you get when making the package?

**Comment by targodan** [comment]
I see... welp. Guess I'll try to deactivate the failing tests by some more nasty patches. I'll try to get around to it by the end of next weekend.

**Comment by anthraxx** [comment]
Awesome, very very much appreciated! silly tests shouldn't depend on running X

**Comment by anthraxx** [comment]
Ok it works now, i just erradicate the X tests, good enough i guess :yum: 
thanks for your work on this, your patch is applied in the tree i just reverted my revert, thx!

gonna hit the repos in short time

**Pull request closed without merging**
