### PR TITLE
updated zmap to v2.1.1-2

### PR DESCRIPTION
**Pull request by archey**
Added in ztree and zblacklist binaries to complete pkg, we are working on adding in zgrab to our repo. It was mentioned in the docs that ztee might be a good addition and its in zmap. However I noticed its not being installed, so I added it to the pkgbuild

### CODE REVIEW

**Comment by archey** [comment]
@anthraxx Any update on this?

**Comment by anthraxx** [comment]
yeah, no worries did not forget you. full of stuff to do but its scheduled

**Comment by archey** [comment]
No problem thanks for the reply

**Comment by anthraxx** [comment]
no problem, thx for contributions.
normally I'm lot faster handling such, but there are lot of stuff that created a peak (rebuilds, updates, sec tracker stuff and also some RL foo :stuck_out_tongue: ) and I needed to prioritize those somehow :smile_cat:

**Comment by anthraxx** [comment]
fixed via 160913978f8bfe063c9367e545e843aba0f34af7 with additional mondodb connector support in e591e29b86d1d36149de7bd15e1a826826e1ed55.
2.1.1-2 will be soon available in the repos

**Pull request closed without merging**
