### PR TITLE
adds proper linking with shared libs closes #1

### PR DESCRIPTION
**Pull request by archey**
Fixes the issue, we were having with the linking to the .so libraries. It may need to rearranged a bit, but the code only lets you do the dynamic linking in the build function.

### CODE REVIEW

**Comment by archey** [comment]
@anthraxx any update on this?

**Comment by anthraxx** [comment]
I'm running the hackover CTF right now, you will need to wait until its over. In the meanwhile i recommend playing https://ctf.hackover.de

**Comment by archey** [comment]
Sounds good. Good luck in the ctf. Id join up but im a bit busy myself
right now.

**Comment by anthraxx** [comment]
Added, however I have altered the patch, next time please be bit more careful:

- its issue #6 not #1 
- don't add trailing whitespaces to unrelated lines
- preserve the PKGBUILD style by always using ${somevar} instead of $somevar
- prefix the pkgname in the commit message as this repo contains more then a single package

on top its recommended to have --skip-build in install when building separately as sometimes some weird problems arise otherwise.

**Comment by anthraxx** [comment]
82f7fb7615c28628486552b19a4bbb3dbd7d3f67

**Pull request closed without merging**
